//! Scenarios generated by the Scenario Builder (`canon/src/rift_canon/scenario.py`)
//! boot the runtime as they are: the story starts, the opening objective can
//! be played to the end and the Director gets a valid context.
//!
//! The `*.scenario.json` fixtures are the builder's output for the
//! `*.world.json` next to them; `canon/tests/test_scenario.py` fails when
//! they drift. No network, no Unreal.

use std::path::PathBuf;

use rift_backend::action::{ActionType, ValidatedAction, WorldEventType};
use rift_backend::director::Trigger;
use rift_backend::narrative::{CheckpointStatus, MissionStatus, NarrativeState, ObjectiveStatus};
use rift_backend::runtime::{Applied, DirectorReport, Runtime, RuntimeWorld};
use rift_backend::session::SessionStore;
use uuid::Uuid;

const MISSION: &str = "opening_conflict";
const RESOLVE: &str = "opening_conflict.resolve";
const REPORT: &str = "opening_conflict.report";
const CHECKPOINT: &str = "opening_conflict_resolved";
const RESOLVED_FLAG: &str = "opening_conflict.resolved";

struct Universe {
    world_bible: &'static str,
    scenario: &'static str,
    universe_id: &'static str,
    start: &'static str,
    /// The opening conflict's characters.
    cast: &'static [&'static str],
    /// The character the player reports to.
    contact: &'static str,
    options: usize,
}

const MATRIX: Universe = Universe {
    world_bible: include_str!("fixtures/scenario_builder/the_matrix.world.json"),
    scenario: include_str!("fixtures/scenario_builder/the_matrix.scenario.json"),
    universe_id: "the_matrix_movie_603",
    start: "nebuchadnezzar",
    cast: &["dozer", "neo", "tank"],
    contact: "dozer",
    options: 2,
};

const HARRY_POTTER: Universe = Universe {
    world_bible: include_str!("fixtures/scenario_builder/harry_potter_1.world.json"),
    scenario: include_str!("fixtures/scenario_builder/harry_potter_1.scenario.json"),
    universe_id: "harry_potter_and_the_philosopher_s_stone_movie_671",
    start: "ollivanders",
    cast: &["harry_potter", "mr_ollivander", "rubeus_hagrid"],
    contact: "mr_ollivander",
    options: 3,
};

const BREAKING_BAD: Universe = Universe {
    world_bible: include_str!("fixtures/director/world_bible_breaking_bad.json"),
    scenario: include_str!("fixtures/scenario_builder/breaking_bad.scenario.json"),
    universe_id: "breaking_bad_tv_1396",
    start: "albuquerque_hospital",
    cast: &["hank_schrader", "walter_white"],
    contact: "walter_white",
    options: 3,
};

struct Rig {
    runtime: Runtime,
    session_id: Uuid,
}

impl Universe {
    fn world(&self) -> RuntimeWorld {
        RuntimeWorld::from_world_bible(self.world_bible)
            .and_then(|world| world.with_scenario_json(self.scenario))
            .expect("generated scenario loads")
    }

    fn rig(&self) -> Rig {
        let runtime = Runtime::new(SessionStore::new()).with_world(self.world());
        let session_id = runtime.create_session().session_id;
        Rig {
            runtime,
            session_id,
        }
    }
}

impl Rig {
    fn narrative(&self) -> NarrativeState {
        self.runtime
            .narrative(self.session_id)
            .expect("the session runs a story")
    }

    fn objective(&self, objective_id: &str) -> ObjectiveStatus {
        let narrative = self.narrative();
        let (_, objective) = narrative.plan.objective(objective_id).unwrap();
        objective.status
    }

    fn mission(&self) -> MissionStatus {
        self.narrative().plan.mission(MISSION).unwrap().status
    }

    fn interact(&self, target: &str) -> Applied {
        self.runtime
            .apply_player_action(&ValidatedAction {
                action_id: Uuid::new_v4(),
                session_id: self.session_id,
                actor_id: "player".into(),
                action_type: ActionType::Interact,
                target: Some(target.to_owned()),
                content: None,
            })
            .expect("the action is accepted")
    }
}

/// Session creation, story start, the first action and the Director's
/// context, for one generated scenario.
async fn boots_and_plays(universe: &Universe) {
    let rig = universe.rig();
    assert_eq!(
        rig.runtime.world().unwrap().universe_id(),
        universe.universe_id
    );

    // The session is created where the story starts, with the cast on stage.
    let session = rig.runtime.sessions().get(rig.session_id).unwrap();
    assert_eq!(session.current_location.as_deref(), Some(universe.start));
    let on_stage: Vec<String> = rig
        .runtime
        .active_npcs(rig.session_id)
        .into_iter()
        .collect();
    assert_eq!(on_stage, universe.cast);

    // The story started: one active mission with its first objective.
    let narrative = rig.narrative();
    assert_eq!(narrative.plan.missions.len(), 1);
    assert_eq!(rig.mission(), MissionStatus::Active);
    let active: Vec<&str> = narrative
        .active_objectives()
        .into_iter()
        .map(|(_, objective)| objective.objective_id.as_str())
        .collect();
    assert_eq!(active, [RESOLVE]);
    assert_eq!(rig.objective(REPORT), ObjectiveStatus::Pending);

    // Something unrelated is accepted and changes nothing in the story.
    let idle = rig.interact("test_door");
    assert_eq!(
        idle.event.event_type,
        WorldEventType::InteractionAcknowledged
    );
    assert!(idle.consequences.is_empty() && idle.follow_up.is_none());

    // Taking a decision option resolves the conflict.
    let applied = rig.interact("choice_1");
    assert_eq!(rig.objective(RESOLVE), ObjectiveStatus::Completed);
    assert_eq!(rig.objective(REPORT), ObjectiveStatus::Active);
    assert!(applied.consequences.iter().any(|event| {
        event.event_type == WorldEventType::ObjectiveUpdated
            && event.target.as_deref() == Some(RESOLVE)
            && event.payload["status"] == "completed"
    }));
    let session = rig.runtime.sessions().get(rig.session_id).unwrap();
    assert_eq!(session.world_flags.get(RESOLVED_FLAG), Some(&true));

    // The Director is given a context that is valid for this universe.
    let follow_up = applied
        .follow_up
        .expect("a completed objective is meaningful");
    let context = follow_up.context.clone().expect("director context");
    assert_eq!(context.universe_id, universe.universe_id);
    assert_eq!(
        context.trigger,
        Trigger::ObjectiveCompleted {
            objective_id: RESOLVE.to_owned()
        }
    );
    assert_eq!(context.validate(), Ok(()));
    let view = context.narrative.as_ref().unwrap();
    assert_eq!(view.missions[0].mission_id, MISSION);
    let resolve = view.objectives.iter().find(|o| o.objective_id == RESOLVE);
    assert_eq!(
        resolve.and_then(|o| o.giver_npc_id.as_deref()),
        Some(universe.contact)
    );
    assert_eq!(
        context.npcs.iter().filter(|npc| npc.active).count(),
        universe.cast.len()
    );

    // The deterministic Director answers and its decision applies.
    let outcome = rig.runtime.complete(follow_up).await;
    assert!(
        !matches!(
            outcome.director,
            DirectorReport::Rejected { .. } | DirectorReport::Failed(_)
        ),
        "{:?}",
        outcome.director
    );

    // Reporting to the contact completes the mission and reaches the beat.
    rig.interact(universe.contact);
    assert_eq!(rig.objective(REPORT), ObjectiveStatus::Completed);
    assert_eq!(rig.mission(), MissionStatus::Completed);
    let narrative = rig.narrative();
    let checkpoint = narrative.plan.checkpoint(CHECKPOINT).unwrap();
    assert_eq!(checkpoint.status, CheckpointStatus::Reached);
}

#[tokio::test]
async fn matrix_scenario_boots_and_plays() {
    boots_and_plays(&MATRIX).await;
}

#[tokio::test]
async fn harry_potter_scenario_boots_and_plays() {
    boots_and_plays(&HARRY_POTTER).await;
}

#[tokio::test]
async fn breaking_bad_scenario_boots_and_plays() {
    boots_and_plays(&BREAKING_BAD).await;
}

#[test]
fn every_decision_option_resolves_the_conflict() {
    for universe in [&MATRIX, &HARRY_POTTER, &BREAKING_BAD] {
        for n in 1..=universe.options {
            let rig = universe.rig();
            rig.interact(&format!("choice_{n}"));
            assert_eq!(
                rig.objective(RESOLVE),
                ObjectiveStatus::Completed,
                "{} option {n}",
                universe.universe_id
            );
        }
        let rig = universe.rig();
        rig.interact(&format!("choice_{}", universe.options + 1));
        assert_eq!(rig.objective(RESOLVE), ObjectiveStatus::Active);
    }
}

#[test]
fn generated_scenarios_refer_only_to_the_world_bible() {
    for universe in [&MATRIX, &HARRY_POTTER, &BREAKING_BAD] {
        let bible: serde_json::Value = serde_json::from_str(universe.world_bible).unwrap();
        let ids = |key: &str| -> Vec<String> {
            bible[key]
                .as_array()
                .unwrap()
                .iter()
                .map(|item| item["id"].as_str().unwrap().to_owned())
                .collect()
        };
        let (characters, locations) = (ids("characters"), ids("locations"));
        let facts = universe.rig().narrative().world;
        assert!(facts.characters.keys().all(|id| characters.contains(id)));
        assert!(facts.locations.iter().all(|id| locations.contains(id)));
    }
}

/// The path `RIFT_WORLD_BIBLE` + `RIFT_SCENARIO` take at backend startup.
#[test]
fn generated_scenarios_load_from_files() {
    let fixtures =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/scenario_builder");
    for name in ["the_matrix", "harry_potter_1"] {
        let world = RuntimeWorld::from_files(
            &fixtures.join(format!("{name}.world.json")),
            Some(&fixtures.join(format!("{name}.scenario.json"))),
        );
        assert!(world.is_ok(), "{name}: {:?}", world.err());
    }
}
